services:
  libreria-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: libreria-app
    ports:
      - "8080:8080"
    volumes:
      - h2_data:/data
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/libreria_db
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - EXTERNAL_API_BOOKS_URL=https://my-json-server.typicode.com/Gabriel-Arriola-UTN/libros/books
    restart: unless-stopped

volumes:
  h2_data:
    driver: local
